name: Java CI with Maven

on:
  push:
    branches: [ "main", "QuangAnh" ]
  pull_request:
    branches: [ "main", "QuangAnh" ]

jobs:
  build:
    strategy:
      fail-fast: false # Chạy song song cả 3 OS, nếu 1 cái lỗi thì 2 cái kia vẫn chạy tiếp
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    # Chỉ định thư mục mặc định chứa file pom.xml
    defaults:
      run:
        working-directory: ./project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Verify with Maven
        run: mvn --batch-mode verify